simpleArgs: &simple-args
  tokenId: 1

test:
  name: Scoring benchmark
  description: >-
    This benchmark measures NFT trading smart contracts for authorization using trust scoring.
  workers:
    number: 1
  rounds:
    - label: Mint(Scoring)
      description: >-
        Mint ERC721 Tokens.
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 20
      workload:
        module: benchmarks/scenario/scoring/mint.js
        arguments:
          << : *simple-args
    - label: Transfer(Scoring)
      description: >-
        Transfer ERC721 Tokens between accounts.
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 20
      workload:
        module: benchmarks/scenario/scoring/transfer.js
        arguments:
          << : *simple-args
